export const WSS_REPLY_SWITCHED_ON_LED = 'SWITCHED_ON_LED'
export const WSS_REPLY_SWITCHED_OFF_LED = 'SWITCHED_OFF_LED'
export const WSS_REPLY_UNEXPECTED_MESSAGE = 'UNEXPECTED_MESSAGE'
export const WSS_REPLY_TEST = 'TEST'
